name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: |
          go build -o drs