name: Release
on: push

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build Binaries
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: |
          mkdir -p builds/compressed
          go get github.com/mitchellh/gox
          gox --output "builds/drs-{{.OS}}-{{.Arch}}"
          cd builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;

      - name: Upload Binaries
        run: |
          HASH=$(git rev-parse --short "$GITHUB_SHA")
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${{ github.actor }} -r ${{ github.event.repository.name }} --replace Latest builds/compressed/