name: Release
on: push

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Build Binaries
        run: |
          mkdir -p builds/compressed
          go get github.com/mitchellh/gox
          gox --output "builds/drs-{{.OS}}-{{.Arch}}" -osarch '!darwin/386 !plan9/386'
          cd builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;

      - name: Upload Binaries
        run: |
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} --delete Latest builds/compressed/
