name: Release
on: push

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19.0'

      - name: Build Binaries
        run: |
          mkdir -p builds/compressed
          go install github.com/mitchellh/gox@latest
          cd cmd/dss
          gox --output "../../builds/dss-{{.OS}}-{{.Arch}}" -osarch '!darwin/386 !plan9/386'
          cd ../../builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;
      - name: Upload Binaries
        run: |
          go install github.com/tcnksm/ghr@latest
          ghr -t ${{ secrets.GITHUB_TOKEN }} --delete Latest builds/compressed/
